export const DEFAULT_THEME_COLORS = {
  primary: '#1976d2',
  secondary: '#dc004e',
  accent: '#ff9800',
  background: '#ffffff',
  surface: '#f5f5f5',
  headerBackground: '#ffffff',
  headerText: '#1a1a1a',
  headerLink: '#1976d2',
  headerIcon: '#666666',
  cardBackground: '#f5f5f5',
  cardText: '#1a1a1a',
  cardMutedText: '#666666',
  cardBorder: '#e0e0e0',
  cardPrice: '#1976d2',
  text: '#1a1a1a',
  mutedText: '#666666',
  border: '#e0e0e0',
  actionPrimary: '#1976d2',
  actionPrimaryText: '#ffffff',
  actionSecondary: '#dc004e',
  actionSecondaryText: '#ffffff',
  link: '#1976d2',
  price: '#1976d2',
  salePrice: '#d32f2f',
  badgeBackground: '#dc004e',
  badgeText: '#ffffff',
  success: '#2e7d32',
  error: '#d32f2f',
  info: '#0288d1',
  warning: '#ed6c02',
}

export const COLOR_ROLE_GROUPS = [
  {
    id: 'brand',
    title: 'Marca',
    description:
      'Identidad visual de la tienda. No debe controlar botones, cards ni header por sí sola.',
    fields: [
      {
        key: 'primary',
        label: 'Marca primaria',
        appliesTo:
          'Acentos de marca, recursos editoriales y detalles de identidad.',
      },
      {
        key: 'secondary',
        label: 'Marca secundaria',
        appliesTo: 'Segunda familia de marca para soportes visuales.',
      },
      {
        key: 'accent',
        label: 'Acento',
        appliesTo:
          'Énfasis puntual, destacados visuales e iconografía editorial.',
      },
    ],
  },
  {
    id: 'layout',
    title: 'Layout base',
    description:
      'Base estructural del sitio. No debe modificar header, card ni botones especializados.',
    fields: [
      {
        key: 'background',
        label: 'Fondo de página',
        appliesTo: 'Canvas general, secciones amplias y fondo del storefront.',
      },
      {
        key: 'surface',
        label: 'Superficie base',
        appliesTo:
          'Bloques genéricos del layout, modales y superficies no especializadas.',
      },
      {
        key: 'text',
        label: 'Texto principal',
        appliesTo: 'Títulos y contenido principal fuera de header y cards.',
      },
      {
        key: 'mutedText',
        label: 'Texto secundario',
        appliesTo: 'Descripciones, metadatos y texto auxiliar fuera de cards.',
      },
      {
        key: 'border',
        label: 'Borde base',
        appliesTo: 'Separadores e inputs genéricos del layout.',
      },
    ],
  },
  {
    id: 'header',
    title: 'Header',
    description:
      'Control exclusivo del encabezado. Estos cambios no deben mover colores de cards ni CTAs.',
    fields: [
      {
        key: 'headerBackground',
        label: 'Header fondo',
        appliesTo: 'Barra superior y contenedor principal del encabezado.',
      },
      {
        key: 'headerText',
        label: 'Header texto',
        appliesTo: 'Marca, títulos y texto informativo dentro del header.',
      },
      {
        key: 'headerLink',
        label: 'Header links',
        appliesTo: 'Navegación textual y links dentro del header.',
      },
      {
        key: 'headerIcon',
        label: 'Header iconos',
        appliesTo: 'Iconos, contadores y acciones visuales del header.',
      },
    ],
  },
  {
    id: 'card',
    title: 'Cards y paneles',
    description:
      'Control exclusivo de tarjetas, paneles y bloques de producto. No debe mover header ni fondo general.',
    fields: [
      {
        key: 'cardBackground',
        label: 'Card fondo',
        appliesTo:
          'Fondo de cards de producto, paneles laterales y bloques elevados.',
      },
      {
        key: 'cardText',
        label: 'Card texto',
        appliesTo: 'Texto principal dentro de cards y paneles.',
      },
      {
        key: 'cardMutedText',
        label: 'Card texto secundario',
        appliesTo: 'Metadatos y descripciones secundarias dentro de cards.',
      },
      {
        key: 'cardBorder',
        label: 'Card borde',
        appliesTo: 'Bordes y contornos de cards, fichas y paneles.',
      },
      {
        key: 'cardPrice',
        label: 'Card precio',
        appliesTo: 'Precio destacado dentro de cards de producto.',
      },
    ],
  },
  {
    id: 'action',
    title: 'Acciones y navegación',
    description:
      'Sistema de CTA y enlaces. Debe controlar interacción, no la identidad global del layout.',
    fields: [
      {
        key: 'actionPrimary',
        label: 'Botón primario',
        appliesTo: 'Relleno de CTAs principales: comprar, guardar, continuar.',
      },
      {
        key: 'actionPrimaryText',
        label: 'Texto botón primario',
        appliesTo: 'Texto e iconos dentro del botón primario.',
      },
      {
        key: 'actionSecondary',
        label: 'Botón secundario',
        appliesTo: 'Relleno o borde de acciones secundarias.',
      },
      {
        key: 'actionSecondaryText',
        label: 'Texto botón secundario',
        appliesTo: 'Texto e iconos dentro del botón secundario.',
      },
      {
        key: 'link',
        label: 'Links generales',
        appliesTo: 'Links fuera del header y fuera de botones.',
      },
    ],
  },
  {
    id: 'commerce',
    title: 'Ecommerce',
    description:
      'Señales comerciales del catálogo. Deben quedar separadas de acciones y layout.',
    fields: [
      {
        key: 'price',
        label: 'Precio general',
        appliesTo: 'Precio fuera de cards, resúmenes y vistas de detalle.',
      },
      {
        key: 'salePrice',
        label: 'Precio oferta',
        appliesTo: 'Ahorro, rebajas y precio promocional.',
      },
      {
        key: 'badgeBackground',
        label: 'Badge fondo',
        appliesTo: 'Etiquetas comerciales como oferta, nuevo o destacado.',
      },
      {
        key: 'badgeText',
        label: 'Badge texto',
        appliesTo: 'Texto dentro de badges y etiquetas comerciales.',
      },
    ],
  },
  {
    id: 'feedback',
    title: 'Estados',
    description:
      'Feedback del sistema: validación, éxito, error, advertencia e información.',
    fields: [
      {
        key: 'success',
        label: 'Éxito',
        appliesTo: 'Mensajes exitosos, confirmaciones y check visual.',
      },
      {
        key: 'error',
        label: 'Error',
        appliesTo: 'Errores, fallos y validaciones negativas.',
      },
      {
        key: 'warning',
        label: 'Advertencia',
        appliesTo: 'Alertas preventivas y avisos de atención.',
      },
      {
        key: 'info',
        label: 'Info',
        appliesTo: 'Estados neutrales, tips y mensajes informativos.',
      },
    ],
  },
]

export const COLOR_PRESETS = [
  {
    name: 'Azul Corporativo',
    primary: '#1565c0',
    secondary: '#ff6f00',
    accent: '#00b8d4',
    background: '#f4f8ff',
    surface: '#ffffff',
    headerBackground: '#0b2f5f',
    headerText: '#ffffff',
    headerLink: '#dbeafe',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#102a43',
    cardMutedText: '#627d98',
    cardBorder: '#d9e8fb',
    cardPrice: '#0b5cad',
    text: '#102a43',
    mutedText: '#627d98',
    border: '#cfe0f5',
    actionPrimary: '#1565c0',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ff6f00',
    actionSecondaryText: '#1f1300',
    link: '#0b5cad',
    price: '#0b5cad',
    salePrice: '#d64545',
    badgeBackground: '#00b8d4',
    badgeText: '#062f36',
    success: '#138a36',
    error: '#d64545',
    info: '#1565c0',
    warning: '#ff9800',
  },
  {
    name: 'Verde Natural',
    primary: '#2e7d32',
    secondary: '#558b2f',
    accent: '#fbc02d',
    background: '#f5f7ed',
    surface: '#fffdf4',
    headerBackground: '#183d1d',
    headerText: '#f8ffe9',
    headerLink: '#dcecc4',
    headerIcon: '#f8ffe9',
    cardBackground: '#fffdf4',
    cardText: '#24381f',
    cardMutedText: '#6c785f',
    cardBorder: '#d8e2c3',
    cardPrice: '#2e7d32',
    text: '#24381f',
    mutedText: '#6c785f',
    border: '#cedbb7',
    actionPrimary: '#2e7d32',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#fbc02d',
    actionSecondaryText: '#2f2500',
    link: '#33691e',
    price: '#2e7d32',
    salePrice: '#b55223',
    badgeBackground: '#dcecc4',
    badgeText: '#1f4a20',
    success: '#2e7d32',
    error: '#c2410c',
    info: '#417b9a',
    warning: '#d99a00',
  },
  {
    name: 'Rosa Moderno',
    primary: '#c2185b',
    secondary: '#7b1fa2',
    accent: '#ffd54f',
    background: '#fff6fb',
    surface: '#ffffff',
    headerBackground: '#3a123f',
    headerText: '#fff7fb',
    headerLink: '#ffd6e7',
    headerIcon: '#fff7fb',
    cardBackground: '#ffffff',
    cardText: '#321024',
    cardMutedText: '#846377',
    cardBorder: '#f4c9dc',
    cardPrice: '#c2185b',
    text: '#321024',
    mutedText: '#846377',
    border: '#efc2d8',
    actionPrimary: '#c2185b',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ffd54f',
    actionSecondaryText: '#3a2800',
    link: '#9c1452',
    price: '#c2185b',
    salePrice: '#e53935',
    badgeBackground: '#ffe3ef',
    badgeText: '#8d1242',
    success: '#2e7d32',
    error: '#d32f2f',
    info: '#7b1fa2',
    warning: '#f9a825',
  },
  {
    name: 'Oscuro Premium',
    primary: '#90caf9',
    secondary: '#f48fb1',
    accent: '#ffe082',
    background: '#121212',
    surface: '#1e1e1e',
    text: '#ffffff',
    mutedText: '#b0b0b0',
    headerBackground: '#181818',
    headerText: '#ffffff',
    cardBackground: '#1f1f1f',
    cardText: '#ffffff',
    cardMutedText: '#b0b0b0',
    cardBorder: '#2f2f2f',
    cardPrice: '#ffe082',
    headerLink: '#c7d2fe',
    headerIcon: '#ffffff',
    border: '#333333',
    actionPrimary: '#90caf9',
    actionPrimaryText: '#0b1220',
    actionSecondary: '#f48fb1',
    actionSecondaryText: '#230612',
    link: '#90caf9',
    price: '#ffe082',
    salePrice: '#ff8a80',
    badgeBackground: '#2f2f2f',
    badgeText: '#ffe082',
    success: '#81c784',
    error: '#ef9a9a',
    info: '#90caf9',
    warning: '#ffe082',
  },
  {
    name: 'Editorial Minimal',
    primary: '#111827',
    secondary: '#6b7280',
    accent: '#c08457',
    background: '#fafafa',
    surface: '#ffffff',
    text: '#111827',
    mutedText: '#6b7280',
    border: '#e5e7eb',
    headerBackground: '#ffffff',
    headerText: '#111827',
    headerLink: '#111827',
    headerIcon: '#4b5563',
    cardBackground: '#ffffff',
    cardText: '#111827',
    cardMutedText: '#6b7280',
    cardBorder: '#e5e7eb',
    cardPrice: '#111827',
    actionPrimary: '#111827',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#c08457',
    actionSecondaryText: '#ffffff',
    link: '#111827',
    price: '#111827',
    salePrice: '#b45309',
    badgeBackground: '#111827',
    badgeText: '#ffffff',
    success: '#15803d',
    error: '#b91c1c',
    info: '#1d4ed8',
    warning: '#b45309',
  },
  {
    name: 'Beauty Soft',
    primary: '#e0637f',
    secondary: '#ffb199',
    accent: '#c98bae',
    background: '#fff9f7',
    surface: '#ffffff',
    text: '#4a2530',
    mutedText: '#9c7481',
    border: '#f6dbe0',
    headerBackground: '#fff9f7',
    headerText: '#4a2530',
    headerLink: '#e0637f',
    headerIcon: '#9c7481',
    cardBackground: '#ffffff',
    cardText: '#4a2530',
    cardMutedText: '#9c7481',
    cardBorder: '#f6dbe0',
    cardPrice: '#e0637f',
    actionPrimary: '#e0637f',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ffb199',
    actionSecondaryText: '#4a2530',
    link: '#c94f6b',
    price: '#e0637f',
    salePrice: '#dc2626',
    badgeBackground: '#ffe1d6',
    badgeText: '#c2410c',
    success: '#16a34a',
    error: '#dc2626',
    info: '#0ea5e9',
    warning: '#ea9a3c',
  },
  {
    name: 'Outdoor Tierra',
    primary: '#166534',
    secondary: '#a16207',
    accent: '#84cc16',
    background: '#f7f6ef',
    surface: '#ffffff',
    text: '#1f2933',
    mutedText: '#64715b',
    border: '#d9decf',
    headerBackground: '#f7f6ef',
    headerText: '#1f2933',
    headerLink: '#166534',
    headerIcon: '#526347',
    cardBackground: '#ffffff',
    cardText: '#1f2933',
    cardMutedText: '#64715b',
    cardBorder: '#d9decf',
    cardPrice: '#166534',
    actionPrimary: '#166534',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#a16207',
    actionSecondaryText: '#ffffff',
    link: '#166534',
    price: '#166534',
    salePrice: '#b91c1c',
    badgeBackground: '#dcfce7',
    badgeText: '#14532d',
    success: '#166534',
    error: '#b91c1c',
    info: '#0369a1',
    warning: '#a16207',
  },
  {
    name: 'Tech Clean',
    primary: '#2563eb',
    secondary: '#0f172a',
    accent: '#6366f1',
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#0f172a',
    mutedText: '#64748b',
    border: '#dbe3ef',
    headerBackground: '#ffffff',
    headerText: '#0f172a',
    headerLink: '#2563eb',
    headerIcon: '#475569',
    cardBackground: '#ffffff',
    cardText: '#0f172a',
    cardMutedText: '#64748b',
    cardBorder: '#dbe3ef',
    cardPrice: '#2563eb',
    actionPrimary: '#2563eb',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#0f172a',
    actionSecondaryText: '#ffffff',
    link: '#2563eb',
    price: '#2563eb',
    salePrice: '#dc2626',
    badgeBackground: '#e0e7ff',
    badgeText: '#3730a3',
    success: '#16a34a',
    error: '#dc2626',
    info: '#06b6d4',
    warning: '#d97706',
  },
  {
    name: 'Kids Pop',
    primary: '#7c3aed',
    secondary: '#f97316',
    accent: '#22c55e',
    background: '#fffdf2',
    surface: '#ffffff',
    text: '#312e81',
    mutedText: '#6b7280',
    border: '#f2e7c9',
    headerBackground: '#fffdf2',
    headerText: '#312e81',
    headerLink: '#7c3aed',
    headerIcon: '#f97316',
    cardBackground: '#ffffff',
    cardText: '#312e81',
    cardMutedText: '#6b7280',
    cardBorder: '#f2e7c9',
    cardPrice: '#7c3aed',
    actionPrimary: '#7c3aed',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#f97316',
    actionSecondaryText: '#ffffff',
    link: '#7c3aed',
    price: '#7c3aed',
    salePrice: '#e11d48',
    badgeBackground: '#dcfce7',
    badgeText: '#166534',
    success: '#22c55e',
    error: '#e11d48',
    info: '#0ea5e9',
    warning: '#eab308',
  },
  {
    name: 'Luxury Nocturno',
    primary: '#d4af37',
    secondary: '#8c7853',
    accent: '#f5e6a8',
    background: '#09090b',
    surface: '#141416',
    text: '#f5f5f4',
    mutedText: '#a1a1aa',
    border: '#2a2a2f',
    headerBackground: '#09090b',
    headerText: '#f5f5f4',
    headerLink: '#d4af37',
    headerIcon: '#d4af37',
    cardBackground: '#141416',
    cardText: '#f5f5f4',
    cardMutedText: '#a1a1aa',
    cardBorder: '#2a2a2f',
    cardPrice: '#d4af37',
    actionPrimary: '#d4af37',
    actionPrimaryText: '#111111',
    actionSecondary: '#f5f5f4',
    actionSecondaryText: '#111111',
    link: '#d4af37',
    price: '#d4af37',
    salePrice: '#f87171',
    badgeBackground: '#d4af37',
    badgeText: '#111111',
    success: '#4ade80',
    error: '#f87171',
    info: '#93c5fd',
    warning: '#fbbf24',
  },
  {
    name: 'Marketplace Global',
    primary: '#4338ca',
    secondary: '#0f766e',
    accent: '#f59e0b',
    background: '#f6f8fb',
    surface: '#ffffff',
    text: '#111827',
    mutedText: '#6b7280',
    border: '#d6dee9',
    headerBackground: '#1e1b4b',
    headerText: '#ffffff',
    headerLink: '#c7d2fe',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#111827',
    cardMutedText: '#6b7280',
    cardBorder: '#dbe4ef',
    cardPrice: '#0f766e',
    actionPrimary: '#4338ca',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#f59e0b',
    actionSecondaryText: '#2b1700',
    link: '#4338ca',
    price: '#0f766e',
    salePrice: '#dc2626',
    badgeBackground: '#fef3c7',
    badgeText: '#92400e',
    success: '#16a34a',
    error: '#dc2626',
    info: '#4338ca',
    warning: '#d97706',
  },
  {
    name: 'Fashion Contrast',
    primary: '#111111',
    secondary: '#ef4444',
    accent: '#f5c542',
    background: '#faf7f2',
    surface: '#ffffff',
    text: '#18181b',
    mutedText: '#71717a',
    border: '#e7dfd3',
    headerBackground: '#111111',
    headerText: '#ffffff',
    headerLink: '#f3f0ea',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#18181b',
    cardMutedText: '#71717a',
    cardBorder: '#e7dfd3',
    cardPrice: '#111111',
    actionPrimary: '#111111',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ef4444',
    actionSecondaryText: '#ffffff',
    link: '#b91c1c',
    price: '#111111',
    salePrice: '#ef4444',
    badgeBackground: '#111111',
    badgeText: '#f5c542',
    success: '#15803d',
    error: '#dc2626',
    info: '#3b82f6',
    warning: '#d97706',
  },
  {
    name: 'Gourmet Artesanal',
    primary: '#7c2d12',
    secondary: '#365314',
    accent: '#ca8a04',
    background: '#fff7ed',
    surface: '#fffbeb',
    text: '#3b2416',
    mutedText: '#8a6b52',
    border: '#edcfaa',
    headerBackground: '#431407',
    headerText: '#fff7ed',
    headerLink: '#fed7aa',
    headerIcon: '#fff7ed',
    cardBackground: '#fffbeb',
    cardText: '#3b2416',
    cardMutedText: '#8a6b52',
    cardBorder: '#f1d6b8',
    cardPrice: '#7c2d12',
    actionPrimary: '#7c2d12',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#365314',
    actionSecondaryText: '#f7fee7',
    link: '#9a3412',
    price: '#7c2d12',
    salePrice: '#be123c',
    badgeBackground: '#fed7aa',
    badgeText: '#7c2d12',
    success: '#4d7c0f',
    error: '#b91c1c',
    info: '#2563eb',
    warning: '#ea580c',
  },
  {
    name: 'Sport Performance',
    primary: '#84cc16',
    secondary: '#0284c7',
    accent: '#f97316',
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#111827',
    mutedText: '#64748b',
    border: '#d9e2ec',
    headerBackground: '#111827',
    headerText: '#f9fafb',
    headerLink: '#d9f99d',
    headerIcon: '#f9fafb',
    cardBackground: '#ffffff',
    cardText: '#111827',
    cardMutedText: '#64748b',
    cardBorder: '#d9e2ec',
    cardPrice: '#365314',
    actionPrimary: '#84cc16',
    actionPrimaryText: '#132006',
    actionSecondary: '#0284c7',
    actionSecondaryText: '#ffffff',
    link: '#0369a1',
    price: '#365314',
    salePrice: '#f97316',
    badgeBackground: '#ecfccb',
    badgeText: '#365314',
    success: '#65a30d',
    error: '#dc2626',
    info: '#0284c7',
    warning: '#f97316',
  },
  {
    name: 'Farmacia Confiable',
    primary: '#0e7490',
    secondary: '#16a34a',
    accent: '#38bdf8',
    background: '#f0fdfa',
    surface: '#ffffff',
    text: '#0f172a',
    mutedText: '#64748b',
    border: '#cbd5e1',
    headerBackground: '#0e7490',
    headerText: '#ffffff',
    headerLink: '#cffafe',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#0f172a',
    cardMutedText: '#64748b',
    cardBorder: '#cbd5e1',
    cardPrice: '#0e7490',
    actionPrimary: '#0e7490',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#16a34a',
    actionSecondaryText: '#ffffff',
    link: '#0e7490',
    price: '#0e7490',
    salePrice: '#dc2626',
    badgeBackground: '#cffafe',
    badgeText: '#0e7490',
    success: '#16a34a',
    error: '#dc2626',
    info: '#0284c7',
    warning: '#d97706',
  },
  {
    name: 'Vino & Enoteca',
    primary: '#6d1b3c',
    secondary: '#8b5e34',
    accent: '#c9a15a',
    background: '#fbf5f0',
    surface: '#ffffff',
    text: '#2b1119',
    mutedText: '#7a5b63',
    border: '#e6d3c8',
    headerBackground: '#2b0a14',
    headerText: '#f5e9de',
    headerLink: '#e8c99b',
    headerIcon: '#f5e9de',
    cardBackground: '#ffffff',
    cardText: '#2b1119',
    cardMutedText: '#7a5b63',
    cardBorder: '#e6d3c8',
    cardPrice: '#6d1b3c',
    actionPrimary: '#6d1b3c',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#c9a15a',
    actionSecondaryText: '#2b1119',
    link: '#8b1e42',
    price: '#6d1b3c',
    salePrice: '#b91c1c',
    badgeBackground: '#c9a15a',
    badgeText: '#2b1119',
    success: '#4d7c0f',
    error: '#b91c1c',
    info: '#6d1b3c',
    warning: '#b45309',
  },
  {
    name: 'Boutique Pastel',
    primary: '#a78bfa',
    secondary: '#f9a8d4',
    accent: '#6ee7b7',
    background: '#fdfcff',
    surface: '#ffffff',
    text: '#3f3557',
    mutedText: '#8a80a3',
    border: '#e9e3f7',
    headerBackground: '#ffffff',
    headerText: '#3f3557',
    headerLink: '#a78bfa',
    headerIcon: '#8a80a3',
    cardBackground: '#ffffff',
    cardText: '#3f3557',
    cardMutedText: '#8a80a3',
    cardBorder: '#e9e3f7',
    cardPrice: '#a78bfa',
    actionPrimary: '#a78bfa',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#f9a8d4',
    actionSecondaryText: '#3f3557',
    link: '#8b5cf6',
    price: '#a78bfa',
    salePrice: '#f472b6',
    badgeBackground: '#fce7f3',
    badgeText: '#9d174d',
    success: '#34d399',
    error: '#fb7185',
    info: '#38bdf8',
    warning: '#fcd34d',
  },
  {
    name: 'Ferretería Industrial',
    primary: '#ea580c',
    secondary: '#1f2937',
    accent: '#facc15',
    background: '#f4f4f5',
    surface: '#ffffff',
    text: '#18181b',
    mutedText: '#52525b',
    border: '#d4d4d8',
    headerBackground: '#1f2937',
    headerText: '#ffffff',
    headerLink: '#fdba74',
    headerIcon: '#facc15',
    cardBackground: '#ffffff',
    cardText: '#18181b',
    cardMutedText: '#52525b',
    cardBorder: '#d4d4d8',
    cardPrice: '#ea580c',
    actionPrimary: '#ea580c',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#1f2937',
    actionSecondaryText: '#ffffff',
    link: '#c2410c',
    price: '#ea580c',
    salePrice: '#dc2626',
    badgeBackground: '#facc15',
    badgeText: '#1f2937',
    success: '#16a34a',
    error: '#dc2626',
    info: '#2563eb',
    warning: '#f59e0b',
  },
  {
    name: 'Joyería Elegante',
    primary: '#1c1c1c',
    secondary: '#b76e79',
    accent: '#e8c4a0',
    background: '#fbfaf8',
    surface: '#ffffff',
    text: '#1c1c1c',
    mutedText: '#7a746e',
    border: '#e5dfd6',
    headerBackground: '#1c1c1c',
    headerText: '#f5efe6',
    headerLink: '#e8c4a0',
    headerIcon: '#e8c4a0',
    cardBackground: '#ffffff',
    cardText: '#1c1c1c',
    cardMutedText: '#7a746e',
    cardBorder: '#e5dfd6',
    cardPrice: '#b76e79',
    actionPrimary: '#1c1c1c',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#b76e79',
    actionSecondaryText: '#ffffff',
    link: '#9c4f5c',
    price: '#b76e79',
    salePrice: '#b91c1c',
    badgeBackground: '#e8c4a0',
    badgeText: '#1c1c1c',
    success: '#4d7c0f',
    error: '#b91c1c',
    info: '#52525b',
    warning: '#b45309',
  },
  {
    name: 'Cafetería Cálida',
    primary: '#6f4e37',
    secondary: '#b5651d',
    accent: '#d4a373',
    background: '#fdf6ec',
    surface: '#ffffff',
    text: '#3c2a1e',
    mutedText: '#8a7361',
    border: '#e8d9c5',
    headerBackground: '#3c2a1e',
    headerText: '#fdf6ec',
    headerLink: '#d4a373',
    headerIcon: '#fdf6ec',
    cardBackground: '#ffffff',
    cardText: '#3c2a1e',
    cardMutedText: '#8a7361',
    cardBorder: '#e8d9c5',
    cardPrice: '#6f4e37',
    actionPrimary: '#6f4e37',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#b5651d',
    actionSecondaryText: '#ffffff',
    link: '#8a5a2e',
    price: '#6f4e37',
    salePrice: '#c1440e',
    badgeBackground: '#d4a373',
    badgeText: '#3c2a1e',
    success: '#4d7c0f',
    error: '#c1440e',
    info: '#3b7a8f',
    warning: '#d97706',
  },
  {
    name: 'Floristería Primavera',
    primary: '#4a7c59',
    secondary: '#e8a0bf',
    accent: '#f4d35e',
    background: '#fbfaf5',
    surface: '#ffffff',
    text: '#2e3d2f',
    mutedText: '#708274',
    border: '#dbe6d6',
    headerBackground: '#f0f7ee',
    headerText: '#2e3d2f',
    headerLink: '#4a7c59',
    headerIcon: '#4a7c59',
    cardBackground: '#ffffff',
    cardText: '#2e3d2f',
    cardMutedText: '#708274',
    cardBorder: '#dbe6d6',
    cardPrice: '#4a7c59',
    actionPrimary: '#4a7c59',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#e8a0bf',
    actionSecondaryText: '#2e3d2f',
    link: '#386641',
    price: '#4a7c59',
    salePrice: '#e0607e',
    badgeBackground: '#fdecef',
    badgeText: '#c9184a',
    success: '#4a7c59',
    error: '#d64545',
    info: '#457b9d',
    warning: '#e09f3e',
  },
  {
    name: 'Gaming Neon',
    primary: '#c026d3',
    secondary: '#22d3ee',
    accent: '#a3e635',
    background: '#0a0a0f',
    surface: '#14141f',
    text: '#f3f0ff',
    mutedText: '#9d9bb5',
    border: '#2a2a3d',
    headerBackground: '#0a0a0f',
    headerText: '#f3f0ff',
    headerLink: '#22d3ee',
    headerIcon: '#c026d3',
    cardBackground: '#14141f',
    cardText: '#f3f0ff',
    cardMutedText: '#9d9bb5',
    cardBorder: '#2a2a3d',
    cardPrice: '#22d3ee',
    actionPrimary: '#c026d3',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#22d3ee',
    actionSecondaryText: '#0a0a0f',
    link: '#e879f9',
    price: '#22d3ee',
    salePrice: '#f472b6',
    badgeBackground: '#c026d3',
    badgeText: '#ffffff',
    success: '#4ade80',
    error: '#f87171',
    info: '#22d3ee',
    warning: '#facc15',
  },
  {
    name: 'Hogar Nórdico',
    primary: '#8a9a7e',
    secondary: '#c9a688',
    accent: '#5c6b57',
    background: '#faf8f5',
    surface: '#ffffff',
    text: '#3a3a35',
    mutedText: '#7d7a72',
    border: '#e5e0d8',
    headerBackground: '#faf8f5',
    headerText: '#3a3a35',
    headerLink: '#5c6b57',
    headerIcon: '#5c6b57',
    cardBackground: '#ffffff',
    cardText: '#3a3a35',
    cardMutedText: '#7d7a72',
    cardBorder: '#e5e0d8',
    cardPrice: '#5c6b57',
    actionPrimary: '#5c6b57',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#c9a688',
    actionSecondaryText: '#3a3a35',
    link: '#5c6b57',
    price: '#5c6b57',
    salePrice: '#b5654a',
    badgeBackground: '#ece7dc',
    badgeText: '#5c6b57',
    success: '#6b8f5e',
    error: '#b5654a',
    info: '#6b8ba3',
    warning: '#c9973f',
  },
  {
    name: 'Bebé & Infantil',
    primary: '#7fb3d5',
    secondary: '#fce38a',
    accent: '#ffb6c1',
    background: '#fdfdfb',
    surface: '#ffffff',
    text: '#384860',
    mutedText: '#8496ab',
    border: '#e2eef5',
    headerBackground: '#eaf4fb',
    headerText: '#384860',
    headerLink: '#4a90c2',
    headerIcon: '#4a90c2',
    cardBackground: '#ffffff',
    cardText: '#384860',
    cardMutedText: '#8496ab',
    cardBorder: '#e2eef5',
    cardPrice: '#4a90c2',
    actionPrimary: '#7fb3d5',
    actionPrimaryText: '#17324a',
    actionSecondary: '#fce38a',
    actionSecondaryText: '#5c4a06',
    link: '#4a90c2',
    price: '#4a90c2',
    salePrice: '#f4978e',
    badgeBackground: '#fce38a',
    badgeText: '#5c4a06',
    success: '#81c784',
    error: '#f4978e',
    info: '#4a90c2',
    warning: '#f4a259',
  },
]
