export const DEFAULT_THEME_COLORS = {
  primary: '#1976d2',
  secondary: '#dc004e',
  accent: '#ff9800',
  background: '#ffffff',
  surface: '#f5f5f5',
  headerBackground: '#ffffff',
  headerText: '#1a1a1a',
  headerLink: '#1976d2',
  headerIcon: '#666666',
  cardBackground: '#f5f5f5',
  cardText: '#1a1a1a',
  cardMutedText: '#666666',
  cardBorder: '#e0e0e0',
  cardPrice: '#1976d2',
  text: '#1a1a1a',
  mutedText: '#666666',
  border: '#e0e0e0',
  actionPrimary: '#1976d2',
  actionPrimaryText: '#ffffff',
  actionSecondary: '#dc004e',
  actionSecondaryText: '#ffffff',
  link: '#1976d2',
  price: '#1976d2',
  salePrice: '#d32f2f',
  badgeBackground: '#dc004e',
  badgeText: '#ffffff',
  success: '#2e7d32',
  error: '#d32f2f',
  info: '#0288d1',
  warning: '#ed6c02',
}

export const COLOR_ROLE_GROUPS = [
  {
    id: 'brand',
    title: 'Marca',
    description:
      'Identidad visual de la tienda. No debe controlar botones, cards ni header por sí sola.',
    fields: [
      {
        key: 'primary',
        label: 'Marca primaria',
        appliesTo: 'Acentos de marca, recursos editoriales y detalles de identidad.',
      },
      {
        key: 'secondary',
        label: 'Marca secundaria',
        appliesTo: 'Segunda familia de marca para soportes visuales.',
      },
      {
        key: 'accent',
        label: 'Acento',
        appliesTo: 'Énfasis puntual, destacados visuales e iconografía editorial.',
      },
    ],
  },
  {
    id: 'layout',
    title: 'Layout base',
    description:
      'Base estructural del sitio. No debe modificar header, card ni botones especializados.',
    fields: [
      {
        key: 'background',
        label: 'Fondo de página',
        appliesTo: 'Canvas general, secciones amplias y fondo del storefront.',
      },
      {
        key: 'surface',
        label: 'Superficie base',
        appliesTo: 'Bloques genéricos del layout, modales y superficies no especializadas.',
      },
      {
        key: 'text',
        label: 'Texto principal',
        appliesTo: 'Títulos y contenido principal fuera de header y cards.',
      },
      {
        key: 'mutedText',
        label: 'Texto secundario',
        appliesTo: 'Descripciones, metadatos y texto auxiliar fuera de cards.',
      },
      {
        key: 'border',
        label: 'Borde base',
        appliesTo: 'Separadores e inputs genéricos del layout.',
      },
    ],
  },
  {
    id: 'header',
    title: 'Header',
    description:
      'Control exclusivo del encabezado. Estos cambios no deben mover colores de cards ni CTAs.',
    fields: [
      {
        key: 'headerBackground',
        label: 'Header fondo',
        appliesTo: 'Barra superior y contenedor principal del encabezado.',
      },
      {
        key: 'headerText',
        label: 'Header texto',
        appliesTo: 'Marca, títulos y texto informativo dentro del header.',
      },
      {
        key: 'headerLink',
        label: 'Header links',
        appliesTo: 'Navegación textual y links dentro del header.',
      },
      {
        key: 'headerIcon',
        label: 'Header iconos',
        appliesTo: 'Iconos, contadores y acciones visuales del header.',
      },
    ],
  },
  {
    id: 'card',
    title: 'Cards y paneles',
    description:
      'Control exclusivo de tarjetas, paneles y bloques de producto. No debe mover header ni fondo general.',
    fields: [
      {
        key: 'cardBackground',
        label: 'Card fondo',
        appliesTo: 'Fondo de cards de producto, paneles laterales y bloques elevados.',
      },
      {
        key: 'cardText',
        label: 'Card texto',
        appliesTo: 'Texto principal dentro de cards y paneles.',
      },
      {
        key: 'cardMutedText',
        label: 'Card texto secundario',
        appliesTo: 'Metadatos y descripciones secundarias dentro de cards.',
      },
      {
        key: 'cardBorder',
        label: 'Card borde',
        appliesTo: 'Bordes y contornos de cards, fichas y paneles.',
      },
      {
        key: 'cardPrice',
        label: 'Card precio',
        appliesTo: 'Precio destacado dentro de cards de producto.',
      },
    ],
  },
  {
    id: 'action',
    title: 'Acciones y navegación',
    description:
      'Sistema de CTA y enlaces. Debe controlar interacción, no la identidad global del layout.',
    fields: [
      {
        key: 'actionPrimary',
        label: 'Botón primario',
        appliesTo: 'Relleno de CTAs principales: comprar, guardar, continuar.',
      },
      {
        key: 'actionPrimaryText',
        label: 'Texto botón primario',
        appliesTo: 'Texto e iconos dentro del botón primario.',
      },
      {
        key: 'actionSecondary',
        label: 'Botón secundario',
        appliesTo: 'Relleno o borde de acciones secundarias.',
      },
      {
        key: 'actionSecondaryText',
        label: 'Texto botón secundario',
        appliesTo: 'Texto e iconos dentro del botón secundario.',
      },
      {
        key: 'link',
        label: 'Links generales',
        appliesTo: 'Links fuera del header y fuera de botones.',
      },
    ],
  },
  {
    id: 'commerce',
    title: 'Ecommerce',
    description: 'Señales comerciales del catálogo. Deben quedar separadas de acciones y layout.',
    fields: [
      {
        key: 'price',
        label: 'Precio general',
        appliesTo: 'Precio fuera de cards, resúmenes y vistas de detalle.',
      },
      {
        key: 'salePrice',
        label: 'Precio oferta',
        appliesTo: 'Ahorro, rebajas y precio promocional.',
      },
      {
        key: 'badgeBackground',
        label: 'Badge fondo',
        appliesTo: 'Etiquetas comerciales como oferta, nuevo o destacado.',
      },
      {
        key: 'badgeText',
        label: 'Badge texto',
        appliesTo: 'Texto dentro de badges y etiquetas comerciales.',
      },
    ],
  },
  {
    id: 'feedback',
    title: 'Estados',
    description: 'Feedback del sistema: validación, éxito, error, advertencia e información.',
    fields: [
      {
        key: 'success',
        label: 'Éxito',
        appliesTo: 'Mensajes exitosos, confirmaciones y check visual.',
      },
      {
        key: 'error',
        label: 'Error',
        appliesTo: 'Errores, fallos y validaciones negativas.',
      },
      {
        key: 'warning',
        label: 'Advertencia',
        appliesTo: 'Alertas preventivas y avisos de atención.',
      },
      {
        key: 'info',
        label: 'Info',
        appliesTo: 'Estados neutrales, tips y mensajes informativos.',
      },
    ],
  },
]

export const COLOR_PRESETS = [
  {
    name: 'Azul Corporativo',
    primary: '#1565c0',
    secondary: '#ff6f00',
    accent: '#00b8d4',
    background: '#f4f8ff',
    surface: '#ffffff',
    headerBackground: '#0b2f5f',
    headerText: '#ffffff',
    headerLink: '#dbeafe',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#102a43',
    cardMutedText: '#627d98',
    cardBorder: '#d9e8fb',
    cardPrice: '#0b5cad',
    text: '#102a43',
    mutedText: '#627d98',
    border: '#cfe0f5',
    actionPrimary: '#1565c0',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ff6f00',
    actionSecondaryText: '#1f1300',
    link: '#0b5cad',
    price: '#0b5cad',
    salePrice: '#d64545',
    badgeBackground: '#00b8d4',
    badgeText: '#062f36',
    success: '#138a36',
    error: '#d64545',
    info: '#1565c0',
    warning: '#ff9800',
  },
  {
    name: 'Verde Natural',
    primary: '#2e7d32',
    secondary: '#558b2f',
    accent: '#fbc02d',
    background: '#f5f7ed',
    surface: '#fffdf4',
    headerBackground: '#183d1d',
    headerText: '#f8ffe9',
    headerLink: '#dcecc4',
    headerIcon: '#f8ffe9',
    cardBackground: '#fffdf4',
    cardText: '#24381f',
    cardMutedText: '#6c785f',
    cardBorder: '#d8e2c3',
    cardPrice: '#2e7d32',
    text: '#24381f',
    mutedText: '#6c785f',
    border: '#cedbb7',
    actionPrimary: '#2e7d32',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#fbc02d',
    actionSecondaryText: '#2f2500',
    link: '#33691e',
    price: '#2e7d32',
    salePrice: '#b55223',
    badgeBackground: '#dcecc4',
    badgeText: '#1f4a20',
    success: '#2e7d32',
    error: '#c2410c',
    info: '#417b9a',
    warning: '#d99a00',
  },
  {
    name: 'Rosa Moderno',
    primary: '#c2185b',
    secondary: '#7b1fa2',
    accent: '#ffd54f',
    background: '#fff6fb',
    surface: '#ffffff',
    headerBackground: '#3a123f',
    headerText: '#fff7fb',
    headerLink: '#ffd6e7',
    headerIcon: '#fff7fb',
    cardBackground: '#ffffff',
    cardText: '#321024',
    cardMutedText: '#846377',
    cardBorder: '#f4c9dc',
    cardPrice: '#c2185b',
    text: '#321024',
    mutedText: '#846377',
    border: '#efc2d8',
    actionPrimary: '#c2185b',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ffd54f',
    actionSecondaryText: '#3a2800',
    link: '#9c1452',
    price: '#c2185b',
    salePrice: '#e53935',
    badgeBackground: '#ffe3ef',
    badgeText: '#8d1242',
    success: '#2e7d32',
    error: '#d32f2f',
    info: '#7b1fa2',
    warning: '#f9a825',
  },
  {
    name: 'Oscuro Premium',
    primary: '#90caf9',
    secondary: '#f48fb1',
    accent: '#ffe082',
    background: '#121212',
    surface: '#1e1e1e',
    text: '#ffffff',
    mutedText: '#b0b0b0',
    headerBackground: '#181818',
    headerText: '#ffffff',
    cardBackground: '#1f1f1f',
    cardText: '#ffffff',
    cardMutedText: '#b0b0b0',
    cardBorder: '#2f2f2f',
    headerLink: '#c7d2fe',
    headerIcon: '#ffffff',
    border: '#333333',
    actionPrimary: '#90caf9',
    actionPrimaryText: '#0b1220',
    actionSecondary: '#f48fb1',
    actionSecondaryText: '#230612',
    link: '#90caf9',
    price: '#ffe082',
    salePrice: '#ff8a80',
    badgeBackground: '#2f2f2f',
    badgeText: '#ffe082',
    success: '#81c784',
    error: '#ef9a9a',
    info: '#90caf9',
    warning: '#ffe082',
  },
  {
    name: 'Editorial Minimal',
    primary: '#111827',
    secondary: '#6b7280',
    accent: '#c08457',
    background: '#fafafa',
    surface: '#ffffff',
    text: '#111827',
    mutedText: '#6b7280',
    border: '#e5e7eb',
    headerBackground: '#ffffff',
    headerText: '#111827',
    headerLink: '#111827',
    headerIcon: '#4b5563',
    cardBackground: '#ffffff',
    cardText: '#111827',
    cardMutedText: '#6b7280',
    cardBorder: '#e5e7eb',
    cardPrice: '#111827',
    actionPrimary: '#111827',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#c08457',
    actionSecondaryText: '#ffffff',
    link: '#111827',
    price: '#111827',
    salePrice: '#b45309',
    badgeBackground: '#111827',
    badgeText: '#ffffff',
  },
  {
    name: 'Beauty Soft',
    primary: '#be185d',
    secondary: '#f9a8d4',
    accent: '#f59e0b',
    background: '#fff7fb',
    surface: '#ffffff',
    text: '#3f172d',
    mutedText: '#8a536d',
    border: '#f3d4e3',
    headerBackground: '#fff7fb',
    headerText: '#3f172d',
    headerLink: '#be185d',
    headerIcon: '#8a536d',
    cardBackground: '#ffffff',
    cardText: '#3f172d',
    cardMutedText: '#8a536d',
    cardBorder: '#f3d4e3',
    cardPrice: '#be185d',
    actionPrimary: '#be185d',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#f59e0b',
    actionSecondaryText: '#3f172d',
    link: '#be185d',
    price: '#be185d',
    salePrice: '#dc2626',
    badgeBackground: '#fce7f3',
    badgeText: '#9d174d',
  },
  {
    name: 'Outdoor Tierra',
    primary: '#166534',
    secondary: '#a16207',
    accent: '#84cc16',
    background: '#f7f6ef',
    surface: '#ffffff',
    text: '#1f2933',
    mutedText: '#64715b',
    border: '#d9decf',
    headerBackground: '#f7f6ef',
    headerText: '#1f2933',
    headerLink: '#166534',
    headerIcon: '#526347',
    cardBackground: '#ffffff',
    cardText: '#1f2933',
    cardMutedText: '#64715b',
    cardBorder: '#d9decf',
    cardPrice: '#166534',
    actionPrimary: '#166534',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#a16207',
    actionSecondaryText: '#ffffff',
    link: '#166534',
    price: '#166534',
    salePrice: '#b91c1c',
    badgeBackground: '#dcfce7',
    badgeText: '#14532d',
  },
  {
    name: 'Tech Clean',
    primary: '#2563eb',
    secondary: '#0f172a',
    accent: '#06b6d4',
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#0f172a',
    mutedText: '#64748b',
    border: '#dbe3ef',
    headerBackground: '#ffffff',
    headerText: '#0f172a',
    headerLink: '#2563eb',
    headerIcon: '#475569',
    cardBackground: '#ffffff',
    cardText: '#0f172a',
    cardMutedText: '#64748b',
    cardBorder: '#dbe3ef',
    cardPrice: '#2563eb',
    actionPrimary: '#2563eb',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#0f172a',
    actionSecondaryText: '#ffffff',
    link: '#2563eb',
    price: '#2563eb',
    salePrice: '#dc2626',
    badgeBackground: '#e0f2fe',
    badgeText: '#075985',
  },
  {
    name: 'Kids Pop',
    primary: '#7c3aed',
    secondary: '#f97316',
    accent: '#22c55e',
    background: '#fffdf2',
    surface: '#ffffff',
    text: '#312e81',
    mutedText: '#6b7280',
    border: '#f2e7c9',
    headerBackground: '#fffdf2',
    headerText: '#312e81',
    headerLink: '#7c3aed',
    headerIcon: '#f97316',
    cardBackground: '#ffffff',
    cardText: '#312e81',
    cardMutedText: '#6b7280',
    cardBorder: '#f2e7c9',
    cardPrice: '#7c3aed',
    actionPrimary: '#7c3aed',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#f97316',
    actionSecondaryText: '#ffffff',
    link: '#7c3aed',
    price: '#7c3aed',
    salePrice: '#e11d48',
    badgeBackground: '#dcfce7',
    badgeText: '#166534',
  },
  {
    name: 'Luxury Nocturno',
    primary: '#d4af37',
    secondary: '#6b7280',
    accent: '#f5e6a8',
    background: '#09090b',
    surface: '#141416',
    text: '#f5f5f4',
    mutedText: '#a1a1aa',
    border: '#2a2a2f',
    headerBackground: '#09090b',
    headerText: '#f5f5f4',
    headerLink: '#d4af37',
    headerIcon: '#d4af37',
    cardBackground: '#141416',
    cardText: '#f5f5f4',
    cardMutedText: '#a1a1aa',
    cardBorder: '#2a2a2f',
    cardPrice: '#d4af37',
    actionPrimary: '#d4af37',
    actionPrimaryText: '#111111',
    actionSecondary: '#f5f5f4',
    actionSecondaryText: '#111111',
    link: '#d4af37',
    price: '#d4af37',
    salePrice: '#f87171',
    badgeBackground: '#d4af37',
    badgeText: '#111111',
  },
  {
    name: 'Marketplace Global',
    primary: '#2563eb',
    secondary: '#0f766e',
    accent: '#f59e0b',
    background: '#f6f8fb',
    surface: '#ffffff',
    text: '#111827',
    mutedText: '#6b7280',
    border: '#d6dee9',
    headerBackground: '#0f172a',
    headerText: '#ffffff',
    headerLink: '#c7d2fe',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#111827',
    cardMutedText: '#6b7280',
    cardBorder: '#dbe4ef',
    cardPrice: '#0f766e',
    actionPrimary: '#2563eb',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#f59e0b',
    actionSecondaryText: '#2b1700',
    link: '#1d4ed8',
    price: '#0f766e',
    salePrice: '#dc2626',
    badgeBackground: '#e0f2fe',
    badgeText: '#075985',
    success: '#16a34a',
    error: '#dc2626',
    info: '#2563eb',
    warning: '#d97706',
  },
  {
    name: 'Fashion Contrast',
    primary: '#111111',
    secondary: '#ef4444',
    accent: '#f5c542',
    background: '#faf7f2',
    surface: '#ffffff',
    text: '#18181b',
    mutedText: '#71717a',
    border: '#e7dfd3',
    headerBackground: '#111111',
    headerText: '#ffffff',
    headerLink: '#f3f0ea',
    headerIcon: '#ffffff',
    cardBackground: '#ffffff',
    cardText: '#18181b',
    cardMutedText: '#71717a',
    cardBorder: '#e7dfd3',
    cardPrice: '#111111',
    actionPrimary: '#111111',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#ef4444',
    actionSecondaryText: '#ffffff',
    link: '#b91c1c',
    price: '#111111',
    salePrice: '#ef4444',
    badgeBackground: '#111111',
    badgeText: '#f5c542',
    success: '#15803d',
    error: '#dc2626',
    info: '#3b82f6',
    warning: '#d97706',
  },
  {
    name: 'Gourmet Artesanal',
    primary: '#7c2d12',
    secondary: '#365314',
    accent: '#f97316',
    background: '#fff7ed',
    surface: '#fffbeb',
    text: '#3b2416',
    mutedText: '#8a6b52',
    border: '#edcfaa',
    headerBackground: '#431407',
    headerText: '#fff7ed',
    headerLink: '#fed7aa',
    headerIcon: '#fff7ed',
    cardBackground: '#fffbeb',
    cardText: '#3b2416',
    cardMutedText: '#8a6b52',
    cardBorder: '#f1d6b8',
    cardPrice: '#7c2d12',
    actionPrimary: '#7c2d12',
    actionPrimaryText: '#ffffff',
    actionSecondary: '#365314',
    actionSecondaryText: '#f7fee7',
    link: '#9a3412',
    price: '#7c2d12',
    salePrice: '#be123c',
    badgeBackground: '#fed7aa',
    badgeText: '#7c2d12',
    success: '#4d7c0f',
    error: '#b91c1c',
    info: '#2563eb',
    warning: '#ea580c',
  },
  {
    name: 'Sport Performance',
    primary: '#84cc16',
    secondary: '#0284c7',
    accent: '#f97316',
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#111827',
    mutedText: '#64748b',
    border: '#d9e2ec',
    headerBackground: '#111827',
    headerText: '#f9fafb',
    headerLink: '#d9f99d',
    headerIcon: '#f9fafb',
    cardBackground: '#ffffff',
    cardText: '#111827',
    cardMutedText: '#64748b',
    cardBorder: '#d9e2ec',
    cardPrice: '#365314',
    actionPrimary: '#84cc16',
    actionPrimaryText: '#132006',
    actionSecondary: '#0284c7',
    actionSecondaryText: '#ffffff',
    link: '#0369a1',
    price: '#365314',
    salePrice: '#f97316',
    badgeBackground: '#ecfccb',
    badgeText: '#365314',
    success: '#65a30d',
    error: '#dc2626',
    info: '#0284c7',
    warning: '#f97316',
  },
]
